export const OPEN_REPAIR_STATUSES = ['RECEIVED', 'DIAGNOSING', 'WAITING_APPROVAL', 'REPAIRING', 'READY_PICKUP'] as const;
export const PENDING_ORDER_STATUSES = ['PENDIENTE', 'CONFIRMADO', 'PREPARANDO'] as const;
